# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # common ssh-private-key
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  # copy to private-key
  config.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    chmod 600 $HOME/.ssh/id_rsa
  SHELL

  config.vm.define "ansible" do |ansible_controller|
    ansible_controller.vm.network "private_network", ip: "192.168.244.130"
    # OS hostname
    ansible_controller.vm.hostname = "demo-ansible.localhost"
    ansible_controller.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      # VM name
      vb.name = "demo-ansible"
    end
    # shared folder
    ansible_controller.vm.synced_folder "../http-ansible-demo", "/ansible-demo", mount_options: ['dmode=755', 'fmode=644']
    # install ansible
    ansible_controller.vm.provision "shell", privileged: true, inline: <<-SHELL
      yum install -y centos-release-ansible26
      yum install -y ansible
    SHELL

  end

  config.vm.define "lb01" do |lb01|
    lb01.vm.network "private_network", ip: "192.168.244.131"
    # OS hostname
    lb01.vm.hostname = "demo-lb01.localhost"
    lb01.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      # VM name
      vb.name = "demo-lb01"
    end
  end

  config.vm.define "www01" do |www01|
    www01.vm.network "private_network", ip: "192.168.244.132"
    # OS hostname
    www01.vm.hostname = "demo-www01.localhost"
    www01.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      # VM name
      vb.name = "demo-www01"
    end
  end

  config.vm.define "www02" do |www02|
    www02.vm.network "private_network", ip: "192.168.244.133"
    # OS hostname
    www02.vm.hostname = "demo-www02.localhost"
    www02.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      # VM name
      vb.name = "demo-www02"
    end
  end
end
