---
- hosts: www
  become: true
  tasks:
    - name: install httpd server
      yum:
        name: httpd
        state: present
    - name: create dummy content
      shell: echo "<h1>$(hostname)</h1>" > /var/www/html/index.html
    - name: enable httpd
      systemd:
        state: restarted
        name: httpd

- hosts: lb
  become: true
  tasks:
    - name: install haproxy
      yum:
        name: haproxy
        state: present
    - name: configure haproxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0644"
    - name: enable haproxy
      systemd:
        state: restarted
        name: haproxy
